### ISSUE TITLE
UnboundLocalError

### ISSUE THREAD

**Issue by kgb0255** [spacetelescope/notebooks#141]
Hello,

I was following the tutorial with the fits file I downloaded, and I'm getting `UnboundLocalError: local variable 'sig' referenced before assignment` for some F606W images (Prop ID 14235, visit # 18 - low t_exp file excluded) when I run TweakReg. Can I get help with this?

<img width="665" alt="Screen Shot 2020-08-01 at 2 41 18 AM" src="https://user-images.githubusercontent.com/57269223/89098970-d7fafe00-d3a0-11ea-9cf4-18a33b5b10a2.png">

**Comment by pllim** [comment]
Hello, can you please elaborate on exactly which tutorial you were using?

**Comment by pllim** [comment]
And exactly which image(s) are you trying to use? https://archive.stsci.edu/proposal_search.php?id=14235&mission=hst

**Comment by pllim** [comment]
cc @catherine-martlin

**Comment by kgb0255** [comment]
I was following align_mosaics. I removed some of the keyword parameters and mine looks like:
```
tweakreg.TweakReg(input_flc, imagefindcfg={'threshold': dictThreshold[field_type[key]],
                 'conv_width': dictConv_width[field_type[key]],'dqbits': 0},
                 minobj=5,
                 shiftfile=False, 
                 updatehdr=False,
                 interactive=False)
```
I was trying to use JCX618010. I excluded jcx618ihq_flc.fits from the dataset because it had low exposure time.

**Comment by pllim** [comment]
Errr... @samanthalh then?

**Comment by samanthalh** [comment]
Hello! After consulting with a software expert, I believe this error is happening because TweakReg can find no matching sources between the images. There is already an improvement coded that changes this warning to something easier to understand and troubleshoot, but it hasn't been released yet. Assuming this is the problem, you can either determine why there are no matches (try adjusting the source finding parameters, the matching criteria, etc.) or disable us2dhist. 

Also, for problems like this where the notebooks have been modified for a new workflow, I would strongly recommend that you submit a help desk ticket here: [https://stsci.service-now.com/hst](https://stsci.service-now.com/hst). Your questions will go right to DrizzlePac experts rather than to the Jupyter notebook maintainers, so you'll get an answer quicker and more directly. 

Hope this helps! 
Samantha
DrizzlePac Help Desk Lead

**Comment by kgb0255** [comment]
Thank you for your feedback! @samanthalh
