### ISSUE TITLE
README needs to be updated with the Drizzlepac notebooks

### ISSUE THREAD

**Issue by ivastar** [spacetelescope/notebooks#51]

**Comment by arfon** [comment]
/ cc @eteq - is there a reason these aren't linked to?

**Comment by eteq** [comment]
The reasons are 1) It was overlooked at the time due to the AAS rush and 2) they *do* appear in the index (https://spacetelescope.github.io/notebooks/).

I would argue that 1 is evidence that we should consider dropping the list in the README and instead rely on the auto-generated index.  Do you have any objections, @arfon or @ivastar ?

**Comment by arfon** [comment]
I would rather update the README until we've styled this page https://spacetelescope.github.io/notebooks/
