### ISSUE TITLE
Can't set convert.py --include argument

### ISSUE THREAD

**Issue by laurenmarietta** [spacetelescope/notebooks#98]
When I try to run `python convert.py --include interm_tesscut_requests`, I get the following error:
```
Traceback (most recent call last):
  File "convert.py", line 29, in <module>
    converted = run_parsed('.', output_type='HTML', args=args)
  File "/Users/lchambers/CSI/nbpages/nbpages/converter.py", line 412, in run_parsed
    exclude=exclude_list, include=include_list, **kwargs)
  File "/Users/lchambers/CSI/nbpages/nbpages/converter.py", line 256, in process_notebooks
    raise ValueError('cannot give both include and exclude patterns at the '
ValueError: cannot give both include and exclude patterns at the same time
```
I see that, even though I am not explicitly setting the `--exclude` argument, the following notebooks are being excluded: 
- Kepler_FFI
- align_multiple_visits
- align_mosaics
- Initialization
- align_sparse_fields
- mask_satellite

These are the notebooks listed on the `exclude_notebooks` file in the branch I'm working on, so that list makes sense. But I think it might be wise to have a way to override that those notebooks are auto-excluded - since the `exclude_notebooks` file is part of the repo - so the `include` argument isn't rendered useless?

**Comment by obviousrebel** [comment]
The convert.py script in this repo is a wrapper for nbpages functionality. It essentially just adds the `--exclude` arg with the parsed values of the exclude_notebooks file. The issue is when the include arg is used when calling this script which basically the same as calling `python convert.py --include xxx --exclude values_in_exclude_notebook_file`
